#!/bin/bash

PID=`cat $OPENSHIFT_RUBY_LOG_DIR/server.pid`
if [ `ps --pid $PID | wc -l` -gt 1 ]; then
        kill $PID
fi

cd $OPENSHIFT_REPO_DIR

nohup bundle exec ruby ./rallybot.rb > $OPENSHIFT_RUBY_LOG_DIR/server.log 2>&1 &
echo $! > $OPENSHIFT_RUBY_LOG_DIR/server.pid
